### PR TITLE
Fix variance not working for strings*

### LINKED ISSUE #201: Make sure the Optimisers can "fall back" to another optimiser if different histogram types

### PR DESCRIPTION
**Pull request by jamadaha**
* By making it so it never tries to run it on a bucket of strings.

- Closes #201

### CODE REVIEW

**Review by kris701 — APPROVED** [review]

File: Jantimizer/QueryOptimiser/Cost/Nodes/JoinEstimateEquiDepthVariance.cs [hunk 1]
```diff
@@ -17,26 +17,30 @@ internal class JoinEstimateEquiDepthVariance : BaseJoinCost
...
+                    comparisonBucketCertainty = vComparisonBucket.StandardDeviation / vComparisonBucket.Range;
+                double certainty = bucketCertainty / comparisonBucketCertainty;
+                if (certainty > 1)
+                    certainty = 1 / certainty;
+                long estimate = (long)(certainty * vBucket.Count);
+                if (estimate == 0)
+                    return 1;
+                else
+                    return estimate;
+            } else
```
Comment (HGinnerup) [inline Jantimizer/QueryOptimiser/Cost/Nodes/JoinEstimateEquiDepthVariance.cs:40]: Missing newline before `else`

**Review by HGinnerup — CHANGES_REQUESTED** [review]

**Review by HGinnerup — APPROVED** [review]
