### PR TITLE
Small fix for SSL authentication error

### LINKED ISSUE #166: MySQL random SSL Authentication Error
Sometimes the MySQL adapter gives a `SSL Authentication Error` error for some reason. Seems to be random

### PR DESCRIPTION
**Pull request by kris701**
closes #166

### CODE REVIEW

File: Jantimizer/DatabaseConnector/Connectors/MySqlConnector.cs [hunk 1]
```diff
@@ -7,6 +8,10 @@ namespace DatabaseConnector.Connectors
 {
     public class MySqlConnector : BaseDbConnector<MySqlConnection, MySqlCommand, MySqlDataAdapter>
     {
+        private int _timeoutCounter = 0;
+        private int _maxTimeout = 10;
```
Comment (HGinnerup) [inline Jantimizer/DatabaseConnector/Connectors/MySqlConnector.cs]: Timeout sounds like time, maybe rename to max attempts?

**Review by HGinnerup — APPROVED** [review]
