### PR TITLE
Variation fix

### LINKED ISSUE #161: The implementation of variance is currently standard deviation
See here:
https://github.com/jamadaha/P6/blob/84ae2855c002cf4a312afa1102a1ffbc5639984a/Jantimizer/Histograms/Models/Histograms/HistogramEquiDepthVariance.cs#L37

As can be seen the square root of the average is taken, which is standard deviation. This might be the correct approach, but if it is we will likely need to rename **a lot**.

### PR DESCRIPTION
**Pull request by kris701**
Fixed so that variation is actually variation and not standard deviation.
Also included standard deviation (in case it is being used in other branches), and set the `Variance`, `Mean` and `StandardDeviation` properties to be double instead, so we can actually use decimal numbers.
closes #161

### CODE REVIEW

File: Jantimizer/Histograms/Models/Histograms/HistogramEquiDepthVariance.cs [hunk 1]
```diff
@@ -42,28 +42,29 @@ protected override void GenerateHistogramFromSorted(List<IComparable> sorted)
...
                 }
                 mean = mean / countValue;
                 for (int bIter = bStart; bIter < bStart + Depth && bIter < sorted.Count; bIter++)
                 {
-                    variance += (int)Math.Pow((int)sorted[bIter] - mean, 2);
+                    variance += Math.Pow(Convert.ToDouble(sorted[bIter]) - (double)mean, 2);
                 }
                 if (countValue > 1 && variance != 0)
-                    variance = (int)Math.Sqrt(variance / countValue - 1);
+                    standardDeviation = Math.Sqrt((double)variance / countValue - 1);
```
Comment (jamadaha) [inline Jantimizer/Histograms/Models/Histograms/HistogramEquiDepthVariance.cs:61]:
```suggestion
                    standardDeviation = Math.Sqrt((double)variance / countValue - 1);
```
```suggestion
                    standardDeviation = Math.Sqrt((double)variance / countValue);
```
-1 is for a sample of the population instead of the whole

Comment (jamadaha) [inline Jantimizer/Histograms/Models/Histograms/HistogramEquiDepthVariance.cs]:
```suggestion
                    standardDeviation = Math.Sqrt((double)variance / countValue - 1);
```
```suggestion
                    standardDeviation = Math.Sqrt((double)variance / countValue);
```
-1 is for a sample of the population instead of the whole

**Review by jamadaha — CHANGES_REQUESTED** [review]

**Review by jamadaha — APPROVED** [review]

**Review by jamadaha — APPROVED** [review]
