### PR TITLE
Estimator Visualiser and Various Fixes

### LINKED ISSUE #284: Make a visualizer for estimator bounding
Modify the estimator so that we can see where the bounds on each table attribute is set.
Maybe also make one for each bounds sweep.

### PR DESCRIPTION
**Pull request by kris701**
* UI fixes
  * Fixed the milestone viewer being caried over between test runs
  * Added propper titles to the milestone viewer and the new estimator visualiser
* Added a visualiser for how the bounds are set for each query. This makes it a lot simpler to debug.
* Fixed a major issue in the `TableAttributeBounder`, where it didnt bound correctly if the table we are bounding against had already been bounded. (This is only an implementation fix, the theoretical version is still the same)
* Fixed an issue with filters, where the "Larger Than" filters would always include the last segment (since it never checked if there where none that fitted the filter)
* Removed redundant tests with the ">=" and "<=" predicates, since we dont handle them anyway
* Fixed an issue with queries that consists of several table attribute predicates, e.g. "... JOIN c ON c.v > b.v AND c.v < a.v", this was parsed as two joins instead of one. Now one of the predicates are just treated as a filter instead
closes #284

### CODE REVIEW

File: Jantimizer/QueryEstimator/Models/EstimatorResult.cs [hunk 1]
```diff
@@ -12,18 +13,24 @@ public class EstimatorResult : ICloneable
...
+            TableAttributeBounds = tableAttributeBounds;
+            FilterBounds = filterBounds;
+            ResultChain = resultChain;
         }
 
         public object Clone()
         {
             if (FromQuery.Clone() is JsonQuery query)
-                return new EstimatorResult(query, EstimatedCardinality, DidXSweeps);
+                return new EstimatorResult(query, DidXSweeps, EstimatedCardinality, TableAttributeBounds, FilterBounds, ResultChain);
```
Comment (HGinnerup) [inline Jantimizer/QueryEstimator/Models/EstimatorResult.cs:33]: `DidXSweeps` sounds like a boolean. Maybe rename to `SweepsDone` or `SweepsDoneCount` ?

**Review by HGinnerup — APPROVED** [review]
