### PR TITLE
Fixed issue with different histogram types

### LINKED ISSUE #173: Fix string colum types attempting to become a EquiDepthVariance histogram

### PR DESCRIPTION
**Pull request by kris701**
closes #173

### CODE REVIEW

File: Jantimizer/Histograms/HistogramSelectors/DepthHistogramSelector.cs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+        public IDepthHistogram GetHistogramDepthOfTypeOrAlt(IDepthHistogram targetType, Type type, string tableName, string attributeName, int depth)
+        {
+            if (targetType.AcceptedTypes.Contains(Type.GetTypeCode(type)))
+                return targetType;
+
+            IDepthHistogram? histogram = null;
+            switch (Type.GetTypeCode(type))
+            {
+                case TypeCode.String:
+                case TypeCode.Double:
```
Comment (jamadaha) [inline Jantimizer/Histograms/HistogramSelectors/DepthHistogramSelector.cs:31]: Was it not made so that doubles work in variance histograms?

**Review by jamadaha — CHANGES_REQUESTED** [review]

**Review by jamadaha — APPROVED** [review]
